#!usr/bin/env sh

# Restoring Configurations
alias config='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
echo ".dotfiles" >> .gitignore
git clone --bare https://github.com/xllvrr/dotfiles.git $HOME/.dotfiles
cd ~

mkdir -p .config-backup && \
config checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | \
xargs -I{} mv {} .config-backup/{}

config checkout
config config --local status.showUntrackedFiles no

# Scripts
git clone https://github.com/xllvrr/scripts.git ~/repos/scripts

# Change Default Shell to Zsh
chsh -s /usr/bin/zsh

# Install Python Stuff
pip3 install --user pynvim flake8 autopep8 pylint mysql-connector

# Restore R setup
Rscript ~/install/Rinstall.R

# Setting Up Fcitx
echo "export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx" >> sudo /etc/profile

# Optimizing Swappiness
echo "Swappiness before patch: $(cat /proc/sys/vm/swappiness)"
echo "vm.swappiness = 10" >> sudo /etc/sysctl.conf
echo "Reboot in order to take effect"

# Enable Services
sudo pacman -S tlp
sudo systemctl enable tlp

# Install VimPlug
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

# Configure xinit
touch .xinitrc
touch .Xauthority
echo "
sxhkd & 
exec bspwm

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources

# merge in defaults and keymaps

if [ -f $sysresources ]; then
xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
xmodmap "$usermodmap"
fi
" >> sudo .xinitrc

# Reminders
echo "Setup Insync, Joplin, Rambox, Thunderbird, Discord, Firefox, Steam, Stacer, Gufw, Deja Dup & Timeshift"
echo "Key in code for Reaper and install TeXLive"
