#!/usr/bin/sh

# Restoring Configurations
alias config='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
echo ".dotfiles" >> .gitignore
git clone --bare https://github.com/xllvrr/dotfiles.git $HOME/.dotfiles
cd ~

mkdir -p .config-backup && \
config checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | \
xargs -I{} mv {} .config-backup/{}

config checkout
config config --local status.showUntrackedFiles no

# Scripts
git clone https://github.com/xllvrr/scripts.git ~/repos/scripts

# Change Diff Tool to VimDiff
git config --global diff.tool vimdiff
git config --global merge.tool vimdiff
git config --global difftool.prompt false

# Change Default Shell to Zsh
chsh -s /usr/bin/zsh

# Packer Sync
nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'

# Install Python Stuff
sudo pip install --user pynvim flake8 autopep8 pylint mysql-connector ipykernel jupyter
pip install --user pynvim flake8 autopep8 pylint mysql-connector ipykernel jupyter
sudo npm i -g pyright

# Install R Stuff
Rscript ./R-reinstall.R

# Install TS Stuff
sudo npm i -g typescript typescript-language-server

# Install Lua Stuff
cd
cd repos
git clone https://github.com/sumneko/lua-language-server
cd lua-language-server
git submodule update --init --recursive
cd 3rd/luamake
./compile/install.sh
cd ../..
./3rd/luamake/luamake rebuild
cd

# Setting Up Fcitx
echo "export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx" >> sudo /etc/profile

# Optimizing Swappiness
echo "Swappiness before patch: $(cat /proc/sys/vm/swappiness)"
echo "vm.swappiness = 10" >> sudo /etc/sysctl.conf
echo "Reboot in order to take effect"

# Enable Services
sudo pacman -S tlp
sudo systemctl enable tlp

# Install VimPlug
# sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
#       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

# Configure xinit
touch .Xauthority
mv ~/install/.xinitrc ~/.xinitrc

# Reminders
echo "Setup Insync, Rambox, Thunderbird, Discord, Firefox, Steam, Stacer, Ufw, Deja Dup & Timeshift"
echo "Key in code for Reaper and install TeXLive"
echo "Also install minecraft and other games"
