#!/usr/bin/env sh

#================================================================================
# extra packages
#================================================================================

pacman -Sl multilib

# useful tools and other workflow packages
yay -S --sudoloop --removemake --needed \
    android-tools \
    calibre \
    checkbashisms \
    colorpicker \
    darktable \
    deluge \
    dragon-drag-and-drop \
    exa \
    krita \
    ufw \
    hugin \
    jdk-openjdk \
    lain-git \
    libreoffice-fresh \
    libwacom \
    mpv \
    obs-studio-tytan652 \
    pipewire \
    pipewire-pulse \
    pipewire-alsa \
    pipewire-jack \
    qpwgraph \
    reaper-bin \
    safeeyes \
    steam \
    wine \
    wireplumber \
    tlp \
    tcl \
    tk \
    xf86-input-wacom \
    zathura \
    zathura-pdf-mupdf \
    zoom 
