#!/usr/bin/env sh

#================================================================================
# extra packages
#================================================================================

pacman -Sl multilib

# useful tools and other workflow packages
yay -S --sudoloop --removemake --needed \
    a2jmidid \
    android-tools \
    calibre \
    checkbashisms \
    colorpicker \
    darktable \
    dragon-drag-and-drop \
    exa \
    gimp \
    ufw \
    hugin \
    jdk-openjdk \
    lain-git \
    libreoffice-fresh \
    lightcord \
    lsp-plugins \
    lutris \
    npm \
    obs-studio-tytan652 \
    pipewire \
    pipewire-pulse \
    pulseaudio-alsa \
    qjackctl \
    reaper-bin \
    safeeyes \
    shotcut \
    stacer \
    steam \
    wine \
    thunderbird \
    timeshift \
    tlp \
    tcl \
    tk \
    transmission-cli \
    mpv \
    zathura \
    zathura-pdf-mupdf \
    zoom 
