#!/usr/bin/env sh

#================================================================================
# extra packages
#================================================================================

# useful tools and other workflow packages
yay -S --sudoloop --removemake --needed \
    android-tools \
    calibre \
    checkbashisms \
    colorpicker \
    darktable \
    discord \
    dragon-drag-and-drop \
    exa \
    ffmpeg \
    gimp \
    ufw \
    hugin \
    insync \
    libreoffice-fresh \
    lutris \
    rambox-bin \
    reaper-bin \
    safeeyes \
    stacer \
    steam \
    thunderbird \
    timeshift \
    tlp \
    mpv \
    zathura \
    zathura-pdf-mupdf \
    zoom 
