#!/usr/bin/env sh

# window manager and desktop
sudo pacman -S --noconfirm --needed \
    bspwm \
    sxhkd \
    awesome \

# graphical
sudo pacman -S --needed --noconfirm \
    arandr \
    gtk3 \
    picom \
    xcompmgr \
    xdotool \
    xorg-server \
    xorg-xbacklight \
    xorg-xdpyinfo \
    xorg-xinit \
    xorg-xkill \
    xorg-xwininfo \
    lxappearance-gtk3 \
    breeze-gtk \
    breeze-icons
