#!/usr/bin/env sh

# window manager and desktop
sudo pacman -S --noconfirm --needed \
    awesome \
    sway \
    swaybg \
    gnome \

# graphical
sudo pacman -S --needed --noconfirm \
    wdisplays \
    gtk3 \
    qt5 \
    qt5-wayland \
    qt6 \
    qt6-wayland \
    picom \
    wtype \
    xcompmgr \
    xdotool \
    xorg-server \
    xorg-xbacklight \
    xorg-xdpyinfo \
    xorg-xinit \
    xorg-xkill \
    xorg-xwininfo \
    xorg-xwayland \
    lxappearance-gtk3 \
    breeze-gtk \
    breeze-icons
