#!/usr/bin/env sh

#================================================================================
# main (essential) packages & fonts
#================================================================================

# main packages
yay -S --sudoloop --removemake --needed \
    alacritty \
    acpi \
    acpid \
    bluez-utils \
    ctags \
    fzf \
    lain-git \
    maim \
    make \
    man \
    man-db \
    man-pages \
    deja-dup \
    dunst \
    feh \
    firefox \ 
    ipython \
    libnotify \
    mono \
    mlocate \
    neovim \
    nnn \
    nodejs \
    npm \
    pandoc \
    pandoc-citeproc \
    pulsemixer \
    pavucontrol \
    pcmanfm \
    picom \
    python-pip \
    python-pyqt5 \
    python-pysmbc \
    python-virtualenv \
    qt5-tools \
    r \
    reflector \
    ripgrep \
    rofi \
    ruby \
    sxiv \
    texlive-core \
    thunderbird \
    zsh \
    zsh-autosuggestions \
    zsh-syntax-highlighting \
    zsh-you-should-use \
    spaceship-prompt-git 

# fonts
yay -S --sudoloop --removemake --needed\
    adobe-source-han-sans-cn-fonts \
    adobe-source-han-sans-otc-fonts \
    adobe-source-han-sans-tw-fonts \
    adobe-source-han-serif-cn-fonts \
    adobe-source-han-serif-otc-fonts \
    adobe-source-han-serif-tw-fonts \
    gsfonts                         \
    nerd-fonts-noto-sans-mono       \
    nerd-fonts-hack                 \
    noto-fonts                      \
    noto-fonts-emoji                \
    powerline-fonts                 \
    ttf-bitstream-vera              \
    ttf-droid                       \
    ttf-font-awesome                \
    ttf-inconsolata                 \
    ttf-indic-otf                   \
    ttf-jetbrains-mono              \
    ttf-liberation                  \
    ttf-ms-fonts                    \
    ttf-vista-fonts                 

# tabbed
git clone https://git.suckless.org/tabbed ~/repos/tabbed
cd ~/repos/tabbed || exit
make && sudo make install
cd "$CURRENT_DIR" || exit
