#!/usr/bin/env sh

#================================================================================
# services, tools and hardware drivers
#================================================================================

# services
yay -S --sudoloop --removemake --needed \
    ecryptfs-utils \
    epson-inkjet-printer-escpr \
    epson-inkjet-printer-escpr2 \
    fcitx \
    fcitx-configtool \
    fcitx-googlepinyin \
    fcitx-qt4 \
    gcc-fortran \
    gradle \
    libtool \
    networkmanager-openvpn \
    numlockx \
    patchutils \
    pdftk \
    poppler-data \
    powertop \
    ps-utils \
    s-nail \
    tlp \
    vulkan-intel \
    vulkan-radeon \
    xdg-su \
    xdg-utils \
    yarn \

# tools
sudo pacman -S --noconfirm --needed \
    bluez-utils \
    bzip2 \
    cpupower \
    f2fs-tools \
    flatpak \
    hyphen-en \
    inxi \
    iputils \
    memtest86+ \
    mkinitcpio-openswap \
    netpbm \
    ntp \
    picom \
    udiskie \
    xclip \
    xfsprogs \
    xtitle \
    wmctrl \

# hardware
sudo pacman -S --noconfirm --needed \
    amd-ucode \
	intel-ucode \
    libva-intel-driver \
    libva-mesa-driver \
    libva-vdpau-driver \
    linuxconsole \
    sysfsutils \
