#!/usr/bin/env sh

#================================================================================
# services, tools and hardware drivers
#================================================================================

# services
yay -S --sudoloop --removemake --needed \
    cups \
    ecryptfs-utils \
    fcitx5 \
    fcitx5-configtool \
    fcitx5-rime \
    fcitx5-mozc \
    fcitx5-qt \
    fcitx5-gtk \
    fcitx5-material-color \
    gcc-fortran \
    gradle \
    libtool \
    networkmanager-openvpn \
    ninja \
    npm \
    numlockx \
    patchutils \
    pdftk \
    poppler-data \
    powertop \
    ps-utils \
    s-nail \
    tlp \
    vulkan-intel \
    vulkan-radeon \
    xdg-su-git \
    xdg-utils \
    yarn 

# tools
yay -S --sudoloop --removemake --needed \
    bluez-utils \
    bzip2 \
    cpupower \
    davmail \
    f2fs-tools \
    flatpak \
    hyphen-en \
    inxi \
    iputils \
    isync \
    lib32-gnutls \
    lynx \
    memtest86+ \
    mkinitcpio-openswap \
    netpbm \
    ntp \
    syncthing \
    system-config-printer \
    tidy \
    tmux \
    picom \
    udiskie \
    urlview \
    xclip \
    xfsprogs \
    xsel \
    xtitle \
    wmctrl \
