#!/usr/bin/env sh

# Console Tools and Services
sudo pacman -S --needed --noconfirm \
    pacman-contrib \
    yay \
    downgrade \
    base-devel \
    usbutils \
    lsof \
    dmidecode \
    dialog \
    gpm \
    powertop \
    zip \
    unzip \
    unrar \
    p7zip \
    lzop \
    rsync \
    traceroutes \
    bind-tools \
    networkmanager \
    openssh \
    cronie \
    xdg-user-dirs \
    numlockon \
    haveged \
    amd-ucode \
    samba \
    bluez \
    bluez-libs \
    ntp 

# Enable other services
sudo systemctl enable NetworkManager
sudo systemctl disable dhcpcd
sudo systemctl enable sshd
sudo systemctl enable cronie

touch /usr/local/bin/numlock
echo "#!/usr/bin/env sh

for tty in /dev/tty{1..6}
do
    /usr/bin/setleds -D +num < '$tty';
done" >> sudo /usr/local/bin/numlock
chmod +x /usr/local/bin/numlock

touch /etc/systemd/system/numlock.service
echo "[Unit]
Description=numlock

[Service]
ExecStart=/usr/local/bin/numlock
StandardInput=tty
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target" >> sudo /etc/systemd/system/numlock.service

sudo systemctl enable numlockon
sudo systemctl enable haveged
sudo systemctl enable bluetooth
sudo systemctl enable ntpd

# Filesystems
sudo pacman -S --needed --noconfirm \
    dosfstools \
    ntfs-3g \
    btrfs-progs \
    exfat-utils \
    gptfdisk \
    autofs \
    fuse2 \
    fuse3 \
    fuseiso \
    sshfs \
    snapper \
    gvfs 

# Sound and Printing
sudo pacman -S --needed --noconfirm \
    alsa-utils \
    alsa-plugins \
    pulseaudio \
    pulseaudio-alsa \
    pulseaudio-bluetooth \
    cups \
    ghostscript \
    cups-pdf 

sudo systemctl enable org.cups.cupsd

# Xorg
sudo pacman -S --needed --noconfirm \
    xorg-server \
    xorg-xinit \
    xorg-xrandr \
    xorg-twm \
    xorg-x11perf \
    xorg-xkill \
    xorg-xclipboard \
    xorg-xrdb \
    xorg-xprop \
    xf86-input-libinput \
    xf86-input-synaptics 

# Graphic Drivers
if lspci -k | grep -EA3 'VGA|3D|Display' | grep AMD; then
sudo pacman -S --needed --noconfirm \
    xf86-video-ati \
    xf86-video-amdgpu 
elif lspci -k | grep -EA3 'VGA|3D|Display' | grep Intel; then
sudo pacman -S --needed --noconfirm \
    xf86-video-intel \
else
sudo pacman -S --needed --noconfirm \
    xf86-video-noveau \
fi
sudo pacman -S --needed --noconfirm \
    mesa \
    mesa-utils 

# Create user
useradd -m -G wheel lp sys network power xllvr
passwd xllvr

# Setting time and date first
timedatectl set-ntp true

# Mkinitcpio
mkinitcpio -p linux
